name: georeminder
description: Any reminder, any place or any time.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.1.3
  location: ^2.3.5
  page_transition: ^1.1.4
  flutter_local_notifications: ^0.8.2
  material_segmented_control: ^2.0.3
  auto_size_text: ^2.1.0
  intl: ^0.16.0
  flutter_google_places: ^0.2.3
  geocoder: ^0.2.1
  google_maps_webservice: ^0.0.14

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
  - family: OpenSans
    fonts:
      - asset: fonts/OpenSans-Light.ttf
        weight: 100
      - asset: fonts/OpenSans-Regular.ttf
      - asset: fonts/OpenSans-SemiBold.ttf
        weight: 500